'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Denomination

    '''<summary>
    '''payment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents payment As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''pnllst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnllst As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''inclpass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inclpass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rpScrollClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpScrollClass As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rpscroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpscroll As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnldenom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnldenom As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlvdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlvdetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblproduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblproduct As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtsrvchr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsrvchr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltrans As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnature As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''plbldue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plbldue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''shrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shrd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''disp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents disp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblsharedtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsharedtotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''denom_in control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents denom_in As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cashDenomInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cashDenomInput As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''remit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents remit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''amt_nt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amt_nt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up1k control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up1k As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt1k control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt1k As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl1k control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1k As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up500 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt500 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl500 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel10 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt200 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl200 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up100 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt100 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl100 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up50 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt50 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl50 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up20 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up10 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txt10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upcoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upcoin As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtcoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcoin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblcoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcoin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uptotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uptotal As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbltotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_can control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_can As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_denom_clr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_denom_clr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_denom_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_denom_update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_prnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_prnt As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_join control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_join As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''denom_out control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents denom_out As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbldenombal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldenombal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bal_nt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bal_nt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb1k control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb1k As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb1k control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb1k As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb500 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb500 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel9 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb200 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb200 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb100 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb100 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb50 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb50 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtb10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblb10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblb10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtbcoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbcoin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblbcoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbcoin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel8 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblbtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbtotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_bal_clr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_bal_clr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_bal_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_bal_update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlprnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlprnt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''damt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents damt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dword As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''camt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents camt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cword As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''trans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trans As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tglh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tglh As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''srvchr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srvchr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''srcwrds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcwrds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btntog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btntog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''printOCBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printOCBtn As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''printCCBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printCCBtn As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''printJrnlBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printJrnlBtn As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''denVouchPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents denVouchPrint As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pbranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbranch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcpt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcptr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcptr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pvno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pacno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pacno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pglh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pglh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p2kcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p2kcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p2kval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p2kval As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p500count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p500count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p500val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p500val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p200count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p200count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p200val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p200val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p100count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p100count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p100val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p100val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p50count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p50count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p50val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p50val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p20count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p20count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p20val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p20val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p10count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p10count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p10val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p10val As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcoin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ptotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ptotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''paiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''premit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents premit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''journalVouchPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journalVouchPrint As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''jpbranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jpbranch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''jpvno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jpvno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''jpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jpdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblglhcr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblglhcr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblglhdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblglhdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltcr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltcr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''jpnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jpnar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''jpaiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jpaiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSecondReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSecondReceipt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pbranch2 control.
    '''</summary>
    Protected WithEvents pbranch2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcpt2 control.
    '''</summary>
    Protected WithEvents lblcpt2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcptr2 control.
    '''</summary>
    Protected WithEvents lblcptr2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pvno2 control.
    '''</summary>
    Protected WithEvents pvno2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pdate2 control.
    '''</summary>
    Protected WithEvents pdate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pacno2 control.
    '''</summary>
    Protected WithEvents pacno2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcid2 control.
    '''</summary>
    Protected WithEvents pcid2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcname2 control.
    '''</summary>
    Protected WithEvents pcname2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pamt2 control.
    '''</summary>
    Protected WithEvents pamt2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''plbldue2 control.
    '''</summary>
    Protected WithEvents plbldue2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnar2 control.
    '''</summary>
    Protected WithEvents pnar2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p2kcount2 control.
    '''</summary>
    Protected WithEvents p2kcount2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p2kval2 control.
    '''</summary>
    Protected WithEvents p2kval2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p500count2 control.
    '''</summary>
    Protected WithEvents p500count2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p500val2 control.
    '''</summary>
    Protected WithEvents p500val2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p200count2 control.
    '''</summary>
    Protected WithEvents p200count2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p200val2 control.
    '''</summary>
    Protected WithEvents p200val2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p100count2 control.
    '''</summary>
    Protected WithEvents p100count2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p100val2 control.
    '''</summary>
    Protected WithEvents p100val2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p50count2 control.
    '''</summary>
    Protected WithEvents p50count2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p50val2 control.
    '''</summary>
    Protected WithEvents p50val2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p20count2 control.
    '''</summary>
    Protected WithEvents p20count2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p20val2 control.
    '''</summary>
    Protected WithEvents p20val2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p10count2 control.
    '''</summary>
    Protected WithEvents p10count2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p10val2 control.
    '''</summary>
    Protected WithEvents p10val2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcoin2 control.
    '''</summary>
    Protected WithEvents pcoin2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ptotal2 control.
    '''</summary>
    Protected WithEvents ptotal2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''paiw2 control.
    '''</summary>
    Protected WithEvents paiw2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''premit2 control.
    '''</summary>
    Protected WithEvents premit2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pacno2_dup control.
    '''</summary>
    Protected WithEvents pacno2_dup As Global.System.Web.UI.WebControls.Label
End Class
