'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DepositReceipt

    '''<summary>
    '''newreceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newreceipt As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM3 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''tabUP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabUP As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnltrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnltrans As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''soa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents soa As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblproduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblproduct As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlact As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbladd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbladd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmobile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgCapture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCapture As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdinfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rd_due control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_due As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rd_duepaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_duepaid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rd_duebalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_duebalance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dsinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsinfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ds_due control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_due As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ds_duepaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_duepaid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ds_duebalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_duebalance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblhed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdlateby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdlateby As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rddue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rddue As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtnod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dsdue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsdue As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtds_nod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtds_nod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpenal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpenal As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtpenalty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpenalty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblcalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcalc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcpt As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel10 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mop As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblsb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_sb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_sb_bal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_sb_bal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstbnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbnk As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''bnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bnk As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''pnlbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbtn As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btn_up_can control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_up_can As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_up_rcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_up_rcpt As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlprnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlprnt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlbtnprnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbtnprnt As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btntog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btntog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pbranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbranch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcpt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcptr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcptr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pvno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pacno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pacno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pglh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pglh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''paiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''premit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents premit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcbranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcbranch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblccpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblccpt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblccptr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblccptr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcvno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcvno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcacno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcacno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcglh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcglh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pccid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pccid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pccname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pccname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcnar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcaiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcaiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcremit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcremit As Global.System.Web.UI.WebControls.Label

    Protected WithEvents txtReprintDate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtReprintTransID As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btn_reprint_submit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlReprintResults As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlBtnReprintResults As Global.System.Web.UI.UpdatePanel
    Protected WithEvents btnReprintClose As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptReprint As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnote As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pcnote As Global.System.Web.UI.WebControls.Label

End Class
