'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InterestPosting

    '''<summary>
    '''intpost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents intpost As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''upint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upint As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''up5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''up6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''inttyp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inttyp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''prd_cap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prd_cap As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtfrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfrm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fd_day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fd_day As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''runMaturedDepPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents runMaturedDepPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''runMaturedDepCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents runMaturedDepCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''pnlbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbtn As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnclr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnclr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtproduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtproduct As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_inw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_inw As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''jspc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jspc As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''disp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents disp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblnet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbyc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbyc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''int_revised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents int_revised As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''int_rev_acn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents int_rev_acn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''int_rev_amt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents int_rev_amt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''byc_caption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents byc_caption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''byc_rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents byc_rev As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_revised control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_revised As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_post_clr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_post_clr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_post control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_post As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_si_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_si_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_si_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_si_prod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_si_day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_si_day As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_si control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_si As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl_bycas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_bycas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''disp_si control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents disp_si As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_si_cint_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_si_cint_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_si_bycas_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_si_bycas_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_si_clr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_si_clr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_si_up control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_si_up As Global.System.Web.UI.WebControls.Button
End Class
