'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LoanReceipt

    '''<summary>
    '''frmrcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmrcpt As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''pnltrans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnltrans As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''soa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents soa As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlact As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblproduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblproduct As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShareHolderNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShareHolderNew As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbladd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbladd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmobile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''phJewelImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phJewelImages As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''imgCapture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCapture As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''jlrecovery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jlrecovery As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_acn_loss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_acn_loss As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_jla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_jla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_actual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_actual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mop As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlsbtrf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlsbtrf As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''sbtrf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sbtrf As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblsb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_sb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_sb_bal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_sb_bal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnltran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnltran As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstbnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbnk As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''bnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bnk As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtnotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlint As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbldcr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldcr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblddr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldbal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldbal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblperiod_d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblperiod_d As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrebated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrebated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblroi_d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblroi_d As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblactualint_d control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblactualint_d As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblccr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblccr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcbal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcbal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblperiod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblperiod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrebateC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrebateC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblroi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblroi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblactualint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblactualint As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtothers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtothers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtins As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''damt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents damt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dword As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''camt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents camt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cword As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlbtns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbtns As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbtn As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_up_can control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_up_can As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_up_rcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_up_rcpt As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlprnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlprnt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlbtnprnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbtnprnt As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btntog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btntog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pbranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbranch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcpt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcptr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcptr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pvno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pacno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pacno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pglh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pglh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''paiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''premit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents premit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcbranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcbranch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblccpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblccpt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblccptr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblccptr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcvno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcvno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcacno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcacno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcglh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcglh As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pccid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pccid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pccname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pccname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcnar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcnar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcaiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcaiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pcremit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcremit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_branch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_branch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_copy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_copy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_no As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_dt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_dt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_acn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_acn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_acc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_cid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_cid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_amt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_amt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_aiw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_aiw As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ovr_sign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ovr_sign As Global.System.Web.UI.WebControls.Label

    Protected WithEvents txtPostalDate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnCalcPostal As Global.System.Web.UI.WebControls.Button
    Protected WithEvents updPostal As Global.System.Web.UI.UpdatePanel
    Protected WithEvents lblPostalCredit As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPostalDebit As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPostalBalance As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPostalPeriod As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPostalROI As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPostalInterest As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPostalFinalAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtReprintDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReprintDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReprintTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReprintTransID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkServiceChargeReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkServiceChargeReceipt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btn_reprint_submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_reprint_submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlReprintResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReprintResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptReprint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptReprint As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnReprintClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReprintClose As Global.System.Web.UI.WebControls.LinkButton
End Class
