'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShareHolders

    '''<summary>
    '''sharereg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sharereg As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txtfrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfrm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_prnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_prnt As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btn_xl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_xl As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''disp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents disp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblshrnos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblshrnos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblnetshrval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnetshrval As Global.System.Web.UI.WebControls.Label
End Class
