'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StandingInstruction

    '''<summary>
    '''pettycash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pettycash As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txtsiacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsiacn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtday As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtsbacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsbacn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cust As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_si_upclr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_si_upclr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_si_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_si_update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_si_can control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_si_can As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtpro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdayd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdayd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_inw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_inw As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvin As Global.System.Web.UI.WebControls.GridView
End Class
