'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class tds

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFY As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnFetch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFetch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtExportFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExportFileName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvTDSReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTDSReport As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtSearchMemberNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchMemberNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnVerifyMember control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerifyMember As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvMemberDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMemberDetails As Global.System.Web.UI.WebControls.GridView
    '''<summary>
    '''ddlDataSource control.
    '''</summary>
    Protected WithEvents ddlDataSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnExport control.
    '''</summary>
    Protected WithEvents btnExport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportCSV control.
    '''</summary>
    Protected WithEvents btnExportCSV As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBatchImport control.
    '''</summary>
    Protected WithEvents btnBatchImport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upgImport control.
    '''</summary>
    Protected WithEvents upgImport As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''lblImportStatus control.
    '''</summary>
    Protected WithEvents lblImportStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litDashboardLog control.
    '''</summary>
    Protected WithEvents litDashboardLog As Global.System.Web.UI.WebControls.Literal
End Class
