-- Run this script in your fiscusdb database to create the TDS Consolidated table
-- This table is used by the Hub to aggregate interest data from all branches.

IF OBJECT_ID('dbo.TDS_Consolidated_Data', 'U') IS NULL 
BEGIN
    CREATE TABLE dbo.TDS_Consolidated_Data (
        MemberNo VARCHAR(50) NOT NULL,
        FinancialYear VARCHAR(9) NOT NULL,
        FirstName VARCHAR(255),
        address VARCHAR(MAX),
        pincode VARCHAR(50),
        mobile VARCHAR(50),
        dob VARCHAR(50),
        PAN VARCHAR(20),
        -- Monthly Interest Breakdowns (RD, FD, RID, SB, KMK + Total per month)
        Apr_RD MONEY DEFAULT 0, Apr_FD MONEY DEFAULT 0, Apr_RID MONEY DEFAULT 0, Apr_SB MONEY DEFAULT 0, Apr_KMK MONEY DEFAULT 0, Apr_Total MONEY DEFAULT 0,
        May_RD MONEY DEFAULT 0, May_FD MONEY DEFAULT 0, May_RID MONEY DEFAULT 0, May_SB MONEY DEFAULT 0, May_KMK MONEY DEFAULT 0, May_Total MONEY DEFAULT 0,
        Jun_RD MONEY DEFAULT 0, Jun_FD MONEY DEFAULT 0, Jun_RID MONEY DEFAULT 0, Jun_SB MONEY DEFAULT 0, Jun_KMK MONEY DEFAULT 0, Jun_Total MONEY DEFAULT 0,
        Jul_RD MONEY DEFAULT 0, Jul_FD MONEY DEFAULT 0, Jul_RID MONEY DEFAULT 0, Jul_SB MONEY DEFAULT 0, Jul_KMK MONEY DEFAULT 0, Jul_Total MONEY DEFAULT 0,
        Aug_RD MONEY DEFAULT 0, Aug_FD MONEY DEFAULT 0, Aug_RID MONEY DEFAULT 0, Aug_SB MONEY DEFAULT 0, Aug_KMK MONEY DEFAULT 0, Aug_Total MONEY DEFAULT 0,
        Sep_RD MONEY DEFAULT 0, Sep_FD MONEY DEFAULT 0, Sep_RID MONEY DEFAULT 0, Sep_SB MONEY DEFAULT 0, Sep_KMK MONEY DEFAULT 0, Sep_Total MONEY DEFAULT 0,
        Oct_RD MONEY DEFAULT 0, Oct_FD MONEY DEFAULT 0, Oct_RID MONEY DEFAULT 0, Oct_SB MONEY DEFAULT 0, Oct_KMK MONEY DEFAULT 0, Oct_Total MONEY DEFAULT 0,
        Nov_RD MONEY DEFAULT 0, Nov_FD MONEY DEFAULT 0, Nov_RID MONEY DEFAULT 0, Nov_SB MONEY DEFAULT 0, Nov_KMK MONEY DEFAULT 0, Nov_Total MONEY DEFAULT 0,
        Dec_RD MONEY DEFAULT 0, Dec_FD MONEY DEFAULT 0, Dec_RID MONEY DEFAULT 0, Dec_SB MONEY DEFAULT 0, Dec_KMK MONEY DEFAULT 0, Dec_Total MONEY DEFAULT 0,
        Jan_RD MONEY DEFAULT 0, Jan_FD MONEY DEFAULT 0, Jan_RID MONEY DEFAULT 0, Jan_SB MONEY DEFAULT 0, Jan_KMK MONEY DEFAULT 0, Jan_Total MONEY DEFAULT 0,
        Feb_RD MONEY DEFAULT 0, Feb_FD MONEY DEFAULT 0, Feb_RID MONEY DEFAULT 0, Feb_SB MONEY DEFAULT 0, Feb_KMK MONEY DEFAULT 0, Feb_Total MONEY DEFAULT 0,
        Mar_RD MONEY DEFAULT 0, Mar_FD MONEY DEFAULT 0, Mar_RID MONEY DEFAULT 0, Mar_SB MONEY DEFAULT 0, Mar_KMK MONEY DEFAULT 0, Mar_Total MONEY DEFAULT 0,
        TotalInterest MONEY DEFAULT 0,
        CONSTRAINT PK_TDS_Consolidated PRIMARY KEY (MemberNo, FinancialYear)
    );
    PRINT 'TDS_Consolidated_Data table created successfully.';
END
ELSE
BEGIN
    PRINT 'TDS_Consolidated_Data table already exists.';
END
GO
