'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserDashBoard

    '''<summary>
    '''dbc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbc As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''dt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblvch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcbal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcbal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldebit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldebit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblgoldrate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblgoldrate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlpc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlpc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblpettycash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpettycash As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldsacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldsacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldsfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldsfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldsdt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldsdt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldsamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldsamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfdacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfdacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfdfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfdfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfddt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfddt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblfdamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfdamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKMKacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKMKacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKMKfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKMKfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKMKdt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKMKdt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKMKamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKMKamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrdacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrdacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrdfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrdfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrddt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrddt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblrdamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrdamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblridacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblridacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblridfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblridfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblriddt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblriddt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblridamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblridamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsbacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsbacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsbfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsbfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsbdt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsbdt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsbamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsbamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldclacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldclacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldclfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldclfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldcldt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldcldt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldclamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldclamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldlacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldlacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldlfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldlfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldldt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldldt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldlamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldlamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbljlacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljlacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbljlfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljlfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbljldt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljldt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbljlamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljlamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmlacn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmlacn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmlfn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmlfn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmldt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmldt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmlamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmlamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rpstaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpstaff As Global.System.Web.UI.WebControls.Repeater
End Class
